#!/bin/bash

# make new files and scripts excutable
sudo chmod +x /usr/share/pidesktop/script/*
sudo chmod +x /usr/share/pidesktop/python/*

# links to make running installation steps easy
sudo ln -sv /usr/share/pidesktop/script/pd-status /usr/bin/pd-status
sudo ln -sv /usr/share/pidesktop/script/pd-clonessd /usr/bin/pd-clonessd
sudo ln -sv /usr/share/pidesktop/python/pd-bootssd.py /usr/bin/pd-bootssd
sudo ln -sv /usr/share/pidesktop/python/pd-fixrtc.py /usr/bin/pd-fixrtc

# uncomment to autoclone SD to SSD
#sudo /usr/share/pidesktop/python/pd-clonessd.py

# enable new sevices
sudo systemctl enable pidesktop-shutdown.service
sudo systemctl enable pidesktop-rtcsync.service
sudo systemctl list-unit-files | grep pidesktop

# fix up the rtc by default
sudo /usr/share/pidesktop/python/pd-fixrtc.py
