#!/bin/bash

# make new files and scripts excutable
sudo chmod +x /usr/share/pidesktop/script/*
sudo chmod +x /usr/share/pidesktop/python/*

# links to make running installation steps easy
sudo ln -s /usr/share/pidesktop/script/pd-clonehd /usr/bin/pd-clonessd
sudo ln -s /usr/share/pidesktop/python/pd-bootssd.py /usr/bin/pd-bootssd
sudo ln -s /usr/share/pidesktop/python/pd-fixrtc.py /usr/bin/pd-fixrtc

# uncomment to autoclone SD to SSD
#sudo /usr/share/pidesktop/python/pd-clonessd.py

sudo systemctl enable pidesktop-shutdown.service
sudo systemctl enable pidesktop-rtcsync.service

# fix up the rtc by default
sudo /usr/share/pidesktop/python/pd-fixrtc.py
