#!/bin/bash

# show script and python files
echo -e "pidesktop\n\n Scripts and python files:\n"
ls -laR /usr/share/pidesktop

# show links to pd- commands
echo -e "\n Links to commands:\n"
ls -la /usr/bin/pd-*

# show sevices
echo -e "\n Systemd services:\n"
sudo systemctl list-unit-files | grep pidesktop

# show RTC hwclock
echo -e "\n Hardware clock:\n"
sudo hwclock -r

# show System clock
echo -e "\n System clock:\n"
date
