#!/bin/bash

# show scripts and python files
echo -e "pidesktop\n\n Script files:\n"
ls -laR /usr/share/pidesktop/*

# show links to pd- commands
echo -e "\n Links to commands:\n"
ls -la /usr/bin/pd-*

# show sevices
echo -e "\n Systemd services:\n"
systemctl --plain --no-legend list-unit-files 'pidesktop-*'

# show RTC hwclock
echo -e "\n System and hardware clocks:\n"
timedatectl status

# show installed version
echo -e "\n Package status:\n"
dpkg -s pidesktop-base
